from app.models.user import serialize_datetime
from app.users.service import public_user_dict
def media_url(media, thumbnail=False): return f"/api/v1/uploads/images/{media.public_id}{'/thumbnail' if thumbnail else ''}" if media else None
def ref(value): return {"id": value.id, "name_zh": value.name_zh, "name_en": value.name_en, "slug": value.slug} if value else None
def step_dict(step): return {"id": step.id, "position": step.position, "title": step.title, "description": step.description, "media_id": step.media_id, "url": media_url(step.media), "thumbnail_url": media_url(step.media, True), "width": step.media.width, "height": step.media.height}
def guide_dict(guide, user=None, detail=False):
    steps = guide.steps
    feedback = {"valid": 0, "possibly_invalid": 0}
    for item in guide.validity_feedback or []: feedback[item.feedback_type] = feedback.get(item.feedback_type, 0) + 1
    fallback_cover = (guide.game_map and guide.game_map.cover_media and media_url(guide.game_map.cover_media, True)) or (guide.hero and guide.hero.avatar_media and media_url(guide.hero.avatar_media, True))
    data = {"id": guide.id, "title": guide.title, "author": public_user_dict(guide.author), "game": ref(guide.game), "hero": ref(guide.hero), "map": ref(guide.game_map), "content_mode": guide.content_mode, "category": guide.category, "side": guide.side, "map_area": guide.map_area, "timing": guide.timing, "game_version": guide.game_version, "validity_status": guide.validity_status, "cover_image": media_url(steps[0].media, True) if steps else fallback_cover, "image_count": len(steps), "step_count": len(steps), "video_only": not steps and bool(guide.video_url), "excerpt": guide.instructions[:180], "tags": guide.tags or [], "created_at": serialize_datetime(guide.created_at), "updated_at": serialize_datetime(guide.updated_at)}
    if detail: data.update({"instructions": guide.instructions, "skill": guide.skill, "aim_reference": guide.aim_reference, "notes": guide.notes, "video_url": guide.video_url, "tested_at": guide.tested_at.isoformat() if guide.tested_at else None, "validity_note": guide.validity_note, "last_confirmed_at": serialize_datetime(guide.last_confirmed_at), "status": guide.status, "moderation_reason": guide.moderation_reason if user and user.id == guide.author_id else None, "steps": [step_dict(step) for step in steps], "validity_feedback": {**feedback, "current_user": next((item.feedback_type for item in guide.validity_feedback or [] if user and item.user_id == user.id), None)}, "can_edit": bool(user and user.id == guide.author_id), "can_delete": bool(user and user.id == guide.author_id)})
    return data
