from app.models.user import serialize_datetime
from app.users.service import public_user_dict
def media_url(media, thumbnail=False): return f"/api/v1/uploads/images/{media.public_id}{'/thumbnail' if thumbnail else ''}" if media else None
def ref(value): return {"id": value.id, "name_zh": value.name_zh, "name_en": value.name_en, "slug": value.slug} if value else None
def step_dict(step): return {"id": step.id, "position": step.position, "title": step.title, "description": step.description, "media_id": step.media_id, "url": media_url(step.media), "thumbnail_url": media_url(step.media, True), "width": step.media.width, "height": step.media.height}
def guide_dict(guide, user=None, detail=False):
    steps = guide.steps; data = {"id": guide.id, "title": guide.title, "author": public_user_dict(guide.author), "game": ref(guide.game), "hero": ref(guide.hero), "map": ref(guide.game_map), "guide_scope": guide.guide_scope, "category": guide.category, "difficulty": guide.difficulty, "side": guide.side, "game_version": guide.game_version, "validity_status": guide.validity_status, "cover_image": media_url(steps[0].media, True) if steps else None, "step_count": len(steps), "excerpt": guide.instructions[:180], "tags": guide.tags or [], "created_at": serialize_datetime(guide.created_at), "updated_at": serialize_datetime(guide.updated_at)}
    if detail: data.update({"instructions": guide.instructions, "map_area": guide.map_area, "skill": guide.skill, "aim_reference": guide.aim_reference, "timing": guide.timing, "notes": guide.notes, "video_url": guide.video_url, "tested_at": guide.tested_at.isoformat() if guide.tested_at else None, "validity_note": guide.validity_note, "last_confirmed_at": serialize_datetime(guide.last_confirmed_at), "status": guide.status, "moderation_reason": guide.moderation_reason if user and user.id == guide.author_id else None, "steps": [step_dict(step) for step in steps], "can_edit": bool(user and user.id == guide.author_id), "can_delete": bool(user and user.id == guide.author_id)})
    return data
