import { useEffect, useState } from 'react'
import { getLifeChapters } from '../../api/life.js'
import LifeImageManager from './LifeImageManager.jsx'

export default function LifePostForm({ initial, chapterId, onSubmit, pending }) {
  const [form, setForm] = useState(() => initial || { title: '', body: '', chapter_id: chapterId || '', location: '', mood: '', tags: [], shot_at: '', visibility: 'public' }); const [images, setImages] = useState(() => initial?.images || []); const [tag, setTag] = useState(''); const [chapters, setChapters] = useState([]); const [error, setError] = useState(null)
  useEffect(() => { getLifeChapters({ page_size: 100, parent_id: 'root' }).then((result) => setChapters(result.data)).catch(() => {}) }, [])
  function addTag() { const value = tag.trim(); if (value && value.length <= 20 && form.tags.length < 10 && !form.tags.includes(value)) setForm({ ...form, tags: [...form.tags, value] }); setTag('') }
  function submit(event) { event.preventDefault(); if (!form.title.trim() || !form.chapter_id || !images.length || images.some((image) => image.uploading || image.error)) return setError('请填写标题、选择章节，并准备至少一张可用图片。'); onSubmit({ ...form, title: form.title.trim(), chapter_id: Number(form.chapter_id), shot_at: form.shot_at ? new Date(form.shot_at).toISOString() : null, media_ids: images.map((image) => image.id) }) }
  return <form className="life-form" onSubmit={submit}><label>标题<input value={form.title} maxLength="100" onChange={(event) => setForm({ ...form, title: event.target.value })} /></label><label>章节<select value={form.chapter_id} onChange={(event) => setForm({ ...form, chapter_id: event.target.value })}><option value="">选择章节</option>{chapters.map((chapter) => <option key={chapter.id} value={chapter.id}>{chapter.name}</option>)}</select></label><label>正文<textarea rows="6" value={form.body || ''} maxLength="5000" onChange={(event) => setForm({ ...form, body: event.target.value })} /></label><div className="life-form__pair"><label>地点<input value={form.location || ''} maxLength="100" onChange={(event) => setForm({ ...form, location: event.target.value })} /></label><label>心情<input value={form.mood || ''} maxLength="30" onChange={(event) => setForm({ ...form, mood: event.target.value })} /></label></div><label>拍摄时间<input type="datetime-local" value={form.shot_at ? form.shot_at.slice(0, 16) : ''} onChange={(event) => setForm({ ...form, shot_at: event.target.value })} /></label><label>可见范围<select value={form.visibility} onChange={(event) => setForm({ ...form, visibility: event.target.value })}><option value="public">公开</option><option value="login_only">仅登录用户</option><option value="private">仅自己</option></select></label><div className="tag-input"><input value={tag} maxLength="20" placeholder="输入标签后按回车" onChange={(event) => setTag(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') { event.preventDefault(); addTag() } }} /><button type="button" onClick={addTag}>添加标签</button>{form.tags.map((item) => <button type="button" key={item} onClick={() => setForm({ ...form, tags: form.tags.filter((tagName) => tagName !== item) })}>{item} ×</button>)}</div><LifeImageManager value={images} onChange={setImages} existingIds={initial?.images.map((image) => image.id) || []} />{error && <p className="form-feedback form-feedback--error">{error}</p>}<button className="button button--primary" disabled={pending}>{pending ? '正在保存…' : '保存日常'}</button></form>
}
