import { apiClient } from './client.js'

async function get(path, params) { const { data } = await apiClient.get(path, { params }); return { data: data.data, meta: data.meta } }
async function send(method, path, payload) { const { data } = await apiClient.request({ method, url: path, data: payload }); return data.data }
export const getAdminSummary = () => send('get', '/admin/summary')
export const getAdminReports = (params) => get('/admin/reports', params)
export const getAdminReport = (id) => send('get', `/admin/reports/${id}`)
export const claimReport = (id) => send('post', `/admin/reports/${id}/claim`)
export const releaseReport = (id) => send('post', `/admin/reports/${id}/release`)
export const resolveReport = (id, payload) => send('post', `/admin/reports/${id}/resolve`, payload)
export const rejectReport = (id, payload) => send('post', `/admin/reports/${id}/reject`, payload)
export const reopenReport = (id) => send('post', `/admin/reports/${id}/reopen`)
export const getAdminUsers = (params) => get('/admin/users', params)
export const getAdminUser = (id) => send('get', `/admin/users/${id}`)
export const updateUserRestrictions = (id, payload) => send('patch', `/admin/users/${id}/restrictions`, payload)
export const updateUserStatus = (id, payload) => send('patch', `/admin/users/${id}/status`, payload)
export const updateUserRole = (id, payload) => send('patch', `/admin/users/${id}/role`, payload)
export const getAdminLifePosts = (params) => get('/admin/content/life-posts', params)
export const getAdminGuides = (params) => get('/admin/content/guides', params)
export const getAdminComments = (params) => get('/admin/content/comments', params)
export const getAdminFeatured = () => get('/admin/content/featured')
export const hideContent = (type, id, payload) => send('post', `/admin/content/${type}/${id}/hide`, payload)
export const restoreContent = (type, id) => send('post', `/admin/content/${type}/${id}/restore`)
export const deleteAdminContent = (type, id) => send('delete', `/admin/content/${type}/${id}`)
export const featureContent = (type, id, payload) => send('post', `/admin/content/${type}/${id}/feature`, payload)
export const unfeatureContent = (type, id) => send('delete', `/admin/content/${type}/${id}/feature`)
export const markGuideInvalid = (id) => send('post', `/admin/guides/${id}/mark-invalid`)
export const hideComment = (id) => send('post', `/admin/comments/${id}/hide`)
export const restoreComment = (id) => send('post', `/admin/comments/${id}/restore`)
export const deleteAdminComment = (id) => send('delete', `/admin/comments/${id}`)
export const getAdminChapters = (params) => get('/admin/chapters', params)
export const getAdminChapter = (id) => send('get', `/admin/chapters/${id}`)
export const approveChapter = (id, payload) => send('post', `/admin/chapters/${id}/approve`, payload)
export const rejectChapter = (id, payload) => send('post', `/admin/chapters/${id}/reject`, payload)
export const updateAdminChapter = (id, payload) => send('patch', `/admin/chapters/${id}`, payload)
export const mergeChapter = (id, payload) => send('post', `/admin/chapters/${id}/merge`, payload)
export const enableChapter = (id) => send('post', `/admin/chapters/${id}/enable`)
export const disableChapter = (id) => send('post', `/admin/chapters/${id}/disable`)
export const setChapterCover = (id, payload) => send('put', `/admin/chapters/${id}/cover`, payload)
export const removeChapterCover = (id) => send('delete', `/admin/chapters/${id}/cover`)
export const getAdminGames = (params) => get('/admin/catalog/games', params)
export const getAdminHeroes = (params) => get('/admin/catalog/heroes', params)
export const getAdminMaps = (params) => get('/admin/catalog/maps', params)
export const getAdminLogs = (params) => get('/admin/logs', params)
export const getAdminLog = (id) => send('get', `/admin/logs/${id}`)
