import { useCallback, useEffect, useState } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import { useAuth } from '../../auth/useAuth.js'
import { createComment, deleteComment, getCommentReplies, getComments } from '../../api/comments.js'
import { favoriteTarget, getInteractionSummary, likeTarget, unfavoriteTarget, unlikeTarget } from '../../api/interactions.js'
import ReportButton from '../reports/ReportButton.jsx'

export default function InteractionPanel({ targetType, targetId }) {
  const auth = useAuth(); const nav = useNavigate(); const location = useLocation()
  const [summary, setSummary] = useState(null); const [comments, setComments] = useState([]); const [body, setBody] = useState(''); const [replyTo, setReplyTo] = useState(null); const [busy, setBusy] = useState(''); const [error, setError] = useState('')
  const load = useCallback(async () => { try { const [nextSummary, result] = await Promise.all([getInteractionSummary(targetType, targetId), getComments({ target_type: targetType, target_id: targetId, page_size: 20 })]); setSummary(nextSummary); setComments(result.data); setError('') } catch (e) { setError(e.message) } }, [targetType, targetId])
  useEffect(() => { const timer = window.setTimeout(load, 0); return () => window.clearTimeout(timer) }, [load])
  function requireLogin() { if (!auth.isAuthenticated) { nav(`/login?next=${encodeURIComponent(location.pathname)}`); return false } return true }
  async function toggle(kind) { if (!requireLogin() || busy || !summary) return; setBusy(kind); try { if (kind === 'like') setSummary(await (summary.viewer.liked ? unlikeTarget : likeTarget)(targetType, targetId)); else { const result = await (summary.viewer.favorited ? unfavoriteTarget : favoriteTarget)(targetType, targetId); setSummary((s) => ({ ...s, viewer: { ...s.viewer, favorited: result.favorited } })) } } catch (e) { setError(e.message) } finally { setBusy('') } }
  async function submit(event) { event.preventDefault(); if (!requireLogin() || busy || !body.trim()) return; setBusy('comment'); try { await createComment({ target_type: targetType, target_id: Number(targetId), body: body.trim(), reply_to_comment_id: replyTo?.id || null }); setBody(''); setReplyTo(null); await load() } catch (e) { setError(e.message) } finally { setBusy('') } }
  async function remove(id) { try { await deleteComment(id); await load() } catch (e) { setError(e.message) } }
  async function more(item) { try { const result = await getCommentReplies(item.id, { page_size: 100 }); setComments((all) => all.map((x) => x.id === item.id ? { ...x, replies: result.data } : x)) } catch (e) { setError(e.message) } }
  return <section className="interaction-panel" aria-label="内容互动"><div className="interaction-bar"><button type="button" aria-label="点赞" aria-pressed={summary?.viewer.liked || false} disabled={!!busy} onClick={() => void toggle('like')}>♡ {summary?.like_count ?? '—'}</button><button type="button" aria-label="收藏" aria-pressed={summary?.viewer.favorited || false} disabled={!!busy} onClick={() => void toggle('favorite')}>☆ {summary?.viewer.favorited ? '已收藏' : '收藏'}</button><span>评论 {summary?.comment_count ?? '—'}</span></div><h2>评论</h2>{auth.isAuthenticated && !auth.user.can_comment ? <p>当前账号暂时不能发表评论。</p> : <form className="comment-composer" onSubmit={submit}>{replyTo && <p>回复 @{replyTo.author.nickname} <button type="button" onClick={() => setReplyTo(null)}>取消</button></p>}<textarea maxLength="500" value={body} onChange={(e) => setBody(e.target.value)} placeholder={auth.isAuthenticated ? '写下友善、具体的评论…' : '登录后参与评论'} disabled={!auth.isAuthenticated || !auth.user?.can_comment} /><div><span>{body.length}/500</span><button disabled={busy === 'comment' || !body.trim()}>{busy === 'comment' ? '发布中…' : '发布'}</button></div></form>}{error && <p className="form-feedback form-feedback--error" role="alert">{error} <button type="button" onClick={() => void load()}>重试</button></p>}{comments.length === 0 ? <p className="state-message">还没有评论，来写第一条吧。</p> : <div className="comment-list">{comments.map((item) => <Comment key={item.id} item={item} onReply={setReplyTo} onDelete={remove} onMore={more} />)}</div>}</section>
}
function Comment({ item, onReply, onDelete, onMore }) { return <article className={`comment ${item.is_reply ? 'comment--reply' : ''}`}><header><strong>{item.author.nickname}</strong><time>{new Date(item.created_at).toLocaleString('zh-CN')}</time></header><p className={item.is_deleted ? 'comment__deleted' : ''}>{item.is_deleted ? '该评论已删除' : <>{item.reply_to_user && <span>回复 @{item.reply_to_user.nickname}：</span>}{item.body}</>}</p>{!item.is_deleted && <div><button type="button" onClick={() => onReply(item)}>回复</button>{item.can_delete && <button type="button" onClick={() => void onDelete(item.id)}>删除</button>}<ReportButton targetType="comment" targetId={item.id} /></div>}{item.replies?.map((reply) => <Comment key={reply.id} item={reply} onReply={onReply} onDelete={onDelete} onMore={onMore} />)}{item.reply_count > (item.replies?.length || 0) && <button type="button" onClick={() => void onMore(item)}>加载全部 {item.reply_count} 条回复</button>}</article> }
