import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { deleteGuide, getGuide, setGuideValidityFeedback } from '../api/guides.js'
import InteractionPanel from '../components/interactions/InteractionPanel.jsx'
import ReportButton from '../components/reports/ReportButton.jsx'
const validity = { unverified: '未验证', valid: '当前有效', possibly_invalid: '可能失效', invalid: '已失效' }
export default function GuideDetailPage() {
  const { id } = useParams(); const nav = useNavigate(); const [state, setState] = useState({ loading: true, data: null, error: null }); const [pending, setPending] = useState(false)
  useEffect(() => { let dead = false; getGuide(id).then((data) => !dead && setState({ loading: false, data, error: null })).catch((error) => !dead && setState({ loading: false, data: null, error })); return () => { dead = true } }, [id])
  if (state.loading) return <section className="guide-detail page-container"><p className="state-message">正在加载点位…</p></section>
  if (state.error) return <section className="guide-detail page-container"><p className="state-message state-message--error">{state.error.message}</p></section>
  const guide = state.data; const back = `/game/${guide.game.slug}/map/${guide.map.slug}/hero/${guide.hero.slug}`
  async function feedback(type) { setPending(true); try { const data = await setGuideValidityFeedback(id, type); setState((s) => ({ ...s, data })) } catch (e) { setState((s) => ({ ...s, error: e })) } finally { setPending(false) } }
  async function remove() { if (!window.confirm('确认删除这个点位吗？')) return; await deleteGuide(id); nav(back) }
  return <article className="guide-detail page-container"><Link className="text-link" to={back}>返回 {guide.map.name_zh} · {guide.hero.name_zh}</Link><p className="eyebrow">{guide.map.name_zh} · {guide.hero.name_zh}</p><h1>{guide.title}</h1><div className={`guide-validity guide-validity--${guide.validity_status}`}>{validity[guide.validity_status]}</div><dl className="guide-meta"><div><dt>分类</dt><dd>{guide.category}</dd></div>{guide.side && <div><dt>攻防方</dt><dd>{guide.side === 'attack' ? '进攻方' : guide.side === 'defense' ? '防守方' : '攻防皆可'}</dd></div>}{guide.map_area && <div><dt>地图区域</dt><dd>{guide.map_area}</dd></div>}{guide.timing && <div><dt>投掷时间 / 时机</dt><dd>{guide.timing}</dd></div>}</dl><p className="guide-detail__instructions">{guide.instructions}</p>{guide.video_url && <p><a href={guide.video_url} target="_blank" rel="noreferrer">打开外部视频 ↗</a></p>}<section><h2>{guide.content_mode === 'steps' ? '分步说明' : '图片说明'}</h2>{guide.steps.map((step) => <article className="guide-step-viewer" key={step.id}>{step.url && <img src={step.url} alt={step.title || guide.title} loading="lazy" />}{step.title && <h3>{step.title}</h3>}{step.description && <p>{step.description}</p>}</article>)}</section>{guide.notes && <section><h2>注意事项</h2><p>{guide.notes}</p></section>}<div className="tag-row">{guide.tags.map((tag) => <span key={tag}>#{tag}</span>)}</div><section><h2>有效性反馈</h2><p>当前反馈：仍有效 {guide.validity_feedback.valid} · 可能失效 {guide.validity_feedback.possibly_invalid}</p><button disabled={pending} onClick={() => void feedback('valid')}>仍然有效</button><button disabled={pending} onClick={() => void feedback('possibly_invalid')}>可能失效</button></section><div className="life-toolbar">{guide.can_edit && <Link className="button" to={`/guide/${guide.id}/edit`}>编辑点位</Link>}{guide.can_delete && <button className="button--danger" onClick={() => void remove()}>删除点位</button>}<ReportButton targetType="game_guide" targetId={guide.id} /></div><InteractionPanel targetType="game_guide" targetId={guide.id} /></article>
}
