import { useCallback, useEffect, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { getMyGuides, getMyLifePosts } from '../api/users.js'
import { deleteGuide } from '../api/guides.js'
import { deleteLifePost } from '../api/life.js'
import GuideCard from '../components/guides/GuideCard.jsx'
import LifePostCard from '../components/life/LifePostCard.jsx'
import Pagination from '../components/life/Pagination.jsx'

function ContentPage({ kind, hidden = false }) { const [params, setParams] = useSearchParams(); const page = Math.max(1, Number(params.get('page') || 1)); const [state, setState] = useState({ loading: true, items: [], meta: null, error: null }); const load = useCallback(() => { setState((current) => ({ ...current, loading: true, error: null })); const query = { page, page_size: 12, status: hidden ? 'hidden' : (params.get('status') || 'published'), sort: params.get('sort') || 'latest' }; (kind === 'life' ? getMyLifePosts({ ...query, visibility: params.get('visibility') || 'all' }) : getMyGuides(query)).then((result) => setState({ loading: false, items: result.data, meta: result.meta, error: null })).catch((error) => setState({ loading: false, items: [], meta: null, error })) }, [hidden, kind, page, params]); useEffect(() => { load() }, [load]); async function remove(item) { if (!window.confirm('确定删除这项内容吗？')) return; try { if (kind === 'life') await deleteLifePost(item.id); else await deleteGuide(item.id); load() } catch (error) { setState((current) => ({ ...current, error })) } } const title = hidden ? '已下架内容' : kind === 'life' ? '我的日常' : '我的教材'; return <section><h2>{title}</h2>{!hidden && <div className="account-tabs"><button onClick={() => setParams({ status: 'published' })}>已发布</button><button onClick={() => setParams({ status: 'hidden' })}>已下架</button></div>}{state.loading ? <p className="state-message">正在加载…</p> : state.error ? <div className="state-message state-message--error"><p>{state.error.message}</p><button onClick={load}>重试</button></div> : state.items.length ? <><div className="card-grid card-grid--three">{state.items.map((item) => <div className="personal-content-card" key={item.id}>{kind === 'life' ? <LifePostCard post={item} /> : <GuideCard guide={item} />}{hidden && item.moderation_reason && <p className="form-feedback form-feedback--error">下架原因：{item.moderation_reason}</p>}<div><Link className="text-link" to={kind === 'life' ? `/life/post/${item.id}/edit` : `/guide/${item.id}/edit`}>编辑</Link><button onClick={() => void remove(item)}>删除</button></div></div>)}</div><Pagination pagination={state.meta?.pagination} onPageChange={(next) => setParams({ ...Object.fromEntries(params), page: String(next) })} /></> : <p className="life-empty">{hidden ? '目前没有已下架内容。' : '这里还没有内容。'}</p>}</section> }
export function MyLifePostsPage() { return <ContentPage kind="life" /> }
export function MyGuidesPage() { return <ContentPage kind="guide" /> }
export function HiddenContentPage() { const [type, setType] = useState('life'); return <><div className="account-tabs"><button aria-pressed={type === 'life'} onClick={() => setType('life')}>日常</button><button aria-pressed={type === 'guide'} onClick={() => setType('guide')}>教材</button></div><ContentPage key={type} kind={type} hidden /></> }
