/* eslint-disable react-hooks/set-state-in-effect */
import { useEffect, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { searchAll, searchByScope } from '../api/search.js'
import Pagination from '../components/life/Pagination.jsx'

const scopes = [['all', '全部'], ['life_chapter', '生活章节'], ['life_post', '日常'], ['game', '游戏'], ['game_hero', '英雄'], ['game_map', '地图'], ['game_guide', '点位'], ['user', '用户']]
const labels = Object.fromEntries(scopes)
function Item({ item }) { const c = item.content; const title = c.name || c.title || c.name_zh || c.nickname; const subtitle = c.excerpt || c.description || c.bio || c.name_en || c.author?.nickname || ''; return <Link className="search-item" to={item.url}><strong>{title}</strong><span>{subtitle}</span><small>{labels[item.type]}</small></Link> }
export default function SearchPage() {
  const [params, setParams] = useSearchParams(); const q = params.get('q') || ''; const scope = scopes.some(([value]) => value === params.get('scope')) ? (params.get('scope') || 'all') : 'all'; const page = Math.max(1, Number(params.get('page') || 1)); const [value, setValue] = useState(q); const [state, setState] = useState({ loading: false, data: null, meta: null, error: null })
  useEffect(() => setValue(q), [q])
  useEffect(() => { if (!q) { setState({ loading: false, data: null, meta: null, error: null }); return } let cancelled = false; setState({ loading: true, data: null, meta: null, error: null }); const request = scope === 'all' ? searchAll({ q, limit_per_group: 5 }) : searchByScope({ q, scope, page, page_size: 20 }); request.then((result) => { if (!cancelled) setState(scope === 'all' ? { loading: false, data: result, meta: null, error: null } : { loading: false, data: result.data, meta: result.meta, error: null }) }).catch((error) => { if (!cancelled) setState({ loading: false, data: null, meta: null, error }) }); return () => { cancelled = true } }, [q, scope, page])
  function submit(event) { event.preventDefault(); const next = value.trim(); setParams(next ? { q: next, scope } : {}) }
  function changeScope(next) { setParams(q ? { q, scope: next } : { scope: next }) }
  return <section className="page-container search-page"><header><p className="eyebrow">全站搜索</p><h1>在映墨里找一找</h1><form onSubmit={submit} className="search-page__form"><input value={value} onChange={(event) => setValue(event.target.value)} placeholder="搜索日常、游戏、教材或用户" aria-label="搜索" /><button className="button button--primary">搜索</button></form></header><div className="search-scopes">{scopes.map(([key, label]) => <button key={key} className={scope === key ? 'is-active' : ''} onClick={() => changeScope(key)}>{label}</button>)}</div>{!q && <p className="life-empty">输入至少一个字，开始搜索。</p>}{state.loading && <p className="state-message">正在搜索…</p>}{state.error && <div className="state-message state-message--error"><p>{state.error.message}</p><button onClick={() => setParams({ q, scope, page: String(page) })}>重试</button></div>}{!state.loading && !state.error && q && scope === 'all' && <div className="search-groups">{Object.entries(state.data?.groups || {}).filter(([, group]) => group.total > 0).map(([kind, group]) => <section key={kind}><div className="discover-section__heading"><h2>{labels[kind]} <small>{group.total}</small></h2><Link to={`/search?q=${encodeURIComponent(q)}&scope=${kind}`}>查看全部</Link></div>{group.items.map((item) => <Item key={`${item.type}-${item.url}`} item={item} />)}</section>)}{Object.values(state.data?.groups || {}).every((group) => group.total === 0) && <p className="life-empty">没有找到相关内容。</p>}</div>}{!state.loading && !state.error && q && scope !== 'all' && <><div className="search-results">{state.data?.map((item) => <Item key={`${item.type}-${item.url}`} item={item} />)}{state.data?.length === 0 && <p className="life-empty">没有找到相关内容。</p>}</div><Pagination pagination={state.meta?.pagination} onPageChange={(next) => setParams({ q, scope, page: String(next) })} /></>}</section>
}
