import { useEffect, useRef, useState } from 'react'
import { createReport } from '../../api/reports.js'

const reasons = [['inappropriate', '不当内容'], ['violence_illegal', '暴力或违法'], ['harassment', '骚扰或仇恨'], ['spam', '垃圾营销'], ['plagiarism', '抄袭'], ['incorrect_tutorial', '教程有误'], ['duplicate', '重复内容'], ['other', '其他']]

export default function ReportDialog({ targetType, targetId, onClose }) {
  const [reason, setReason] = useState(''); const [description, setDescription] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const closeRef = useRef(null)
  useEffect(() => { closeRef.current?.focus(); const onKey = (event) => { if (event.key === 'Escape' && !busy) onClose() }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey) }, [busy, onClose])
  async function submit(event) { event.preventDefault(); if (!reason || (reason === 'other' && !description.trim()) || busy) return; setBusy(true); setError(''); try { const result = await createReport({ target_type: targetType, target_id: Number(targetId), reason, description: description.trim() || undefined }); if (result.already_exists) { setError('你已提交过对此对象的举报。'); setBusy(false); return } onClose() } catch (nextError) { setError(nextError.message); setBusy(false) } }
  return <div className="report-dialog__backdrop" role="presentation"><section className="report-dialog" role="dialog" aria-modal="true" aria-labelledby="report-title"><header><h2 id="report-title">举报内容</h2><button ref={closeRef} type="button" onClick={onClose} disabled={busy} aria-label="关闭举报窗口">×</button></header><form onSubmit={submit}><label>举报原因<select value={reason} onChange={(event) => setReason(event.target.value)} disabled={busy} required><option value="">请选择原因</option>{reasons.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>补充说明{reason === 'other' && '（必填）'}<textarea value={description} maxLength="1000" onChange={(event) => setDescription(event.target.value)} disabled={busy} placeholder="请简要说明情况" /></label><small>{description.length}/1000</small>{error && <p className="form-feedback form-feedback--error" role="alert">{error}</p>}<footer><button type="button" onClick={onClose} disabled={busy}>取消</button><button className="button button--primary" disabled={busy || !reason || (reason === 'other' && !description.trim())}>{busy ? '正在提交…' : '提交举报'}</button></footer></form></section></div>
}
